packages:
  - "packages/*"
allowBuilds:
  aws-sdk: false
  cpu-features: false
  protobufjs: false
  ssh2: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - "@aws-sdk/client-dynamodb"
  - "@aws-sdk/core"
  - "@aws-sdk/credential-provider-env"
  - "@aws-sdk/credential-provider-http"
  - "@aws-sdk/credential-provider-ini"
  - "@aws-sdk/credential-provider-login"
  - "@aws-sdk/credential-provider-node"
  - "@aws-sdk/credential-provider-process"
  - "@aws-sdk/credential-provider-sso"
  - "@aws-sdk/credential-provider-web-identity"
  - "@aws-sdk/dynamodb-codec"
  - "@aws-sdk/endpoint-cache"
  - "@aws-sdk/middleware-endpoint-discovery"
  - "@aws-sdk/nested-clients"
  - "@aws-sdk/signature-v4-multi-region"
  - "@aws-sdk/token-providers"
  - "@aws-sdk/types"
  - "@aws-sdk/util-locate-window"
  - "@aws-sdk/xml-builder"
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint/parser"
  - "@typescript-eslint/project-service"
  - "@typescript-eslint/scope-manager"
  - "@typescript-eslint/tsconfig-utils"
  - "@typescript-eslint/type-utils"
  - "@typescript-eslint/types"
  - "@typescript-eslint/typescript-estree"
  - "@typescript-eslint/utils"
  - "@typescript-eslint/visitor-keys"
  - "@protobufjs/eventemitter"
  - "electron-to-chromium"
  - "node-releases"
  - "protobufjs"
